version: "3.9"

services:

  cowrie:
    image: "cowrie/cowrie:latest"
    container_name: "cowrie-honeypot"
    restart: unless-stopped
    ports:
      - "2222:2222"
    volumes:
      - "./cowrie-log:/cowrie/cowrie-git/var/log/cowrie"
      - "./cowrie-lib/tty:/cowrie/cowrie-git/var/lib/cowrie/tty"
      - "./cowrie-lib/downloads:/cowrie/cowrie-git/var/lib/cowrie/downloads"
      - "./motd:/cowrie/cowrie-git/honeyfs/etc/motd"
      - "./userdb.txt:/cowrie/cowrie-git/etc/userdb.txt"

  winnrie:
    image: "ozeliurs/winnrie:latest"
    container_name: "winnrie"
    restart: unless-stopped
    volumes:
      - "./cowrie-log:/app/log"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.winnrie.rule=Host(`winnrie.${BASE_DOMAIN}`)"
      - "traefik.http.routers.winnrie.entrypoints=websecure"
      - "traefik.http.routers.winnrie.tls.certresolver=cloudflare"
      - "traefik.http.routers.winnrie.tls=true"
      - "traefik.http.routers.winnrie.service=winnrie"
      - "traefik.http.services.winnrie.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
