version: "3.9"

services:

  hello-world:
    image: "cowrie/cowrie:latest"
    container_name: "cowrie-honeypot"
    restart: unless-stopped
    ports:
      - "2222:2222"
    volumes:
      - "./cowrie-log:/cowrie/cowrie-git/var/log/cowrie"
      - "./cowrie-lib:/cowrie/cowrie-git/var/lib/cowrie"
      - "./motd:/cowrie/cowrie-git/honeyfs/etc/motd"
      - "./userdb.txt:/cowrie/cowrie-git/etc/userdb.txt"