version: "3.9"

services:

  hello-world:
    image: "cowrie/cowrie:latest"
    container_name: "cowrie-honeypot"
    restart: unless-stopped
    ports:
      - "2222:2222"
    volumes:
      - "./cowrie-log:/var/log/cowrie"
      - "./cowrie-lib:/var/lib/cowrie"
      - "./userdb.txt:/etc/userdb.txt"
      - "./motd:/honeyfs/etc/motd"
