version: "3.9"

services:

  hello-world:
    image: "cowrie/cowrie:latest"
    container_name: "cowrie-honeypot"
    restart: unless-stopped
    ports:
      - "2222:2222"
    volumes:
      - "./cowrie:/cowrie"